### ISSUE TITLE
0.3.5 problem with Get Tracks

### ISSUE THREAD

**Issue by Barry4679** [bwilczynski/sonos-cli#11]
I installed your app on Windows. It runs well. ... Thanks.
All good except this issue.

my command was sonos get tracks -p 4
where the 4 was the id of one of the playlists that I retrieved via sonos get playlists

The error is:

> D:\My Documents\Python\sonos-cli-master\sonos>sonos get tracks -p 4
> Traceback (most recent call last):
>   File "c:\program files\python38\lib\runpy.py", line 193, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "c:\program files\python38\lib\runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "C:\Program Files\Python38\Scripts\sonos.exe\__main__.py", line 7, in <module>
>   File "c:\program files\python38\lib\site-packages\click\core.py", line 829, in __call__
>     return self.main(*args, **kwargs)
>   File "c:\program files\python38\lib\site-packages\click\core.py", line 782, in main
>     rv = self.invoke(ctx)
>   File "c:\program files\python38\lib\site-packages\click\core.py", line 1259, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "c:\program files\python38\lib\site-packages\click\core.py", line 1259, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "c:\program files\python38\lib\site-packages\click\core.py", line 1066, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "c:\program files\python38\lib\site-packages\click\core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "C:\Users\xxxxx\AppData\Roaming\Python\Python38\site-packages\sonos_cli-0.3.5-py3.8.egg\sonos\decorators.py", line 58, in wrapper_login_required
>     return func(*args, **kwargs)
>   File "C:\Users\xxxxx\AppData\Roaming\Python\Python38\site-packages\sonos_cli-0.3.5-py3.8.egg\sonos\decorators.py", line 37, in wrapper_format_result
>     print_table()
>   File "C:\Users\xxxxx\AppData\Roaming\Python\Python38\site-packages\sonos_cli-0.3.5-py3.8.egg\sonos\decorators.py", line 24, in print_table
>     rows = [[row[header] for header in headers] for row in table_data]
>   File "C:\Users\xxxxx\AppData\Roaming\Python\Python38\site-packages\sonos_cli-0.3.5-py3.8.egg\sonos\decorators.py", line 24, in <listcomp>
>     rows = [[row[header] for header in headers] for row in table_data]
>   File "C:\Users\xxxxx\AppData\Roaming\Python\Python38\site-packages\sonos_cli-0.3.5-py3.8.egg\sonos\decorators.py", line 24, in <listcomp>
>     rows = [[row[header] for header in headers] for row in table_data]
> KeyError: 'name'

Debug in Get.py, in statement 49 in the Tracks function,  shows
```
result
{'id': '4', 'name': 'Anne 1', 'type': 'playlistSummary', 'tracks': [{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}]}
len(result['tracks'])
100
```

It seems to be trying to download something ... is strange that the dict at result['tracks'] has 100 entries, because the playlist has 104 tracks.

**Comment by bwilczynski** [comment]
Hmm... is it only for this particular playlist? Or you're getting it for the others as well?

**Comment by Barry4679** [comment]
It happens with every playlist that I have tried.
