### ISSUE TITLE
sonos next error: 410 Gone for url

### ISSUE THREAD

**Issue by benwoodward** [bwilczynski/sonos-cli#12]
```
❯ sonos next
Traceback (most recent call last):
  File "/usr/local/bin/sonos", line 11, in <module>
    load_entry_point('sonos-cli==0.3.5', 'console_scripts', 'sonos')()
  File "/usr/local/Cellar/sonos-cli/0.3.5/libexec/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/sonos-cli/0.3.5/libexec/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/sonos-cli/0.3.5/libexec/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/sonos-cli/0.3.5/libexec/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/sonos-cli/0.3.5/libexec/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/sonos-cli/0.3.5/libexec/lib/python3.7/site-packages/sonos/decorators.py", line 58, in wrapper_login_required
    return func(*args, **kwargs)
  File "/usr/local/Cellar/sonos-cli/0.3.5/libexec/lib/python3.7/site-packages/sonos/commands/next.py", line 12, in next
    control.skip_to_next_track(group_id)
  File "/usr/local/Cellar/sonos-cli/0.3.5/libexec/lib/python3.7/site-packages/sonos/decorators.py", line 80, in wrapper_auto_refresh_token
    return func(*args, **kwargs)
  File "/usr/local/Cellar/sonos-cli/0.3.5/libexec/lib/python3.7/site-packages/sonos/api/control.py", line 58, in skip_to_next_track
    return _json(response)
  File "/usr/local/Cellar/sonos-cli/0.3.5/libexec/lib/python3.7/site-packages/sonos/api/control.py", line 21, in _json
    response.raise_for_status()
  File "/usr/local/Cellar/sonos-cli/0.3.5/libexec/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 410 Client Error: Gone for url: https://api.ws.sonos.com/control/api/v1/groups/RINCON_omitted:omitted/playback/skipToNextTrack
```

**Comment by bwilczynski** [comment]
When your active group changes its ID you need to set in again to the proper one. You can check that in ~/.sonos-cli/group.json the id no longer points to any of the the groups returned by: `sonos get groups`

**Comment by bwilczynski** [comment]
Probably needs to be handled better but for now that's how it works.

**Comment by benwoodward** [comment]
Thanks for the explanation.
